2020-05-30T21:00:58.1453045+07:00 0HM04K7GCEPR9:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44318/   (ca22a1cb)
2020-05-30T21:00:58.1453058+07:00 0HM04K7GCEPR8:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:58335/  0 (ca22a1cb)
2020-05-30T21:00:58.2079935+07:00 0HM04K7GCEPR8:00000001 [INF] Request finished in 58.1963ms 200  (791a596a)
2020-05-30T21:00:58.6631043+07:00 0HM04K7GCEPR9:00000001 [INF] Request finished in 523.6148ms 404  (791a596a)
2020-05-30T21:01:08.4512137+07:00 0HM04K7GCEPR8:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44318/swagger   (ca22a1cb)
2020-05-30T21:01:08.4571219+07:00 0HM04K7GCEPR8:00000002 [INF] Request finished in 5.7552ms 301  (791a596a)
2020-05-30T21:01:08.4612298+07:00 0HM04K7GCEPR9:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44318/swagger/index.html   (ca22a1cb)
2020-05-30T21:01:08.5619145+07:00 0HM04K7GCEPR9:00000002 [INF] Request finished in 101.1142ms 200 text/html (791a596a)
2020-05-30T21:01:08.6045088+07:00 0HM04K7GCEPR9:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:44318/swagger/swagger-ui-bundle.js   (ca22a1cb)
2020-05-30T21:01:08.6057483+07:00 0HM04K7GCEPR8:00000003 [INF] Request starting HTTP/1.1 GET http://localhost:44318/swagger/swagger-ui.css   (ca22a1cb)
2020-05-30T21:01:08.6079809+07:00 0HM04K7GCEPRA:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44318/swagger/swagger-ui-standalone-preset.js   (ca22a1cb)
2020-05-30T21:01:08.6596222+07:00 0HM04K7GCEPR8:00000003 [INF] Sending file. Request path: '"/swagger-ui.css"'. Physical path: '"N/A"' (27b0a520)
2020-05-30T21:01:08.6954688+07:00 0HM04K7GCEPRA:00000001 [INF] Sending file. Request path: '"/swagger-ui-standalone-preset.js"'. Physical path: '"N/A"' (27b0a520)
2020-05-30T21:01:08.7014646+07:00 0HM04K7GCEPR9:00000003 [INF] Sending file. Request path: '"/swagger-ui-bundle.js"'. Physical path: '"N/A"' (27b0a520)
2020-05-30T21:01:08.7090030+07:00 0HM04K7GCEPRA:00000001 [INF] Request finished in 90.263ms 200 application/javascript (791a596a)
2020-05-30T21:01:08.7182262+07:00 0HM04K7GCEPR9:00000003 [INF] Request finished in 104.5302ms 200 application/javascript (791a596a)
2020-05-30T21:01:08.7198091+07:00 0HM04K7GCEPR8:00000003 [INF] Request finished in 93.7264ms 200 text/css (791a596a)
2020-05-30T21:01:08.9725208+07:00 0HM04K7GCEPR8:00000004 [INF] Request starting HTTP/1.1 GET http://localhost:44318/swagger/v1/swagger.json   (ca22a1cb)
2020-05-30T21:01:09.0118852+07:00 0HM04K7GCEPRA:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44318/swagger/favicon-32x32.png   (ca22a1cb)
2020-05-30T21:01:09.0278228+07:00 0HM04K7GCEPRA:00000002 [INF] Sending file. Request path: '"/favicon-32x32.png"'. Physical path: '"N/A"' (27b0a520)
2020-05-30T21:01:09.0342332+07:00 0HM04K7GCEPRA:00000002 [INF] Request finished in 21.6775ms 200 image/png (791a596a)
2020-05-30T21:01:09.2691125+07:00 0HM04K7GCEPR8:00000004 [INF] Request finished in 290.1628ms 200 application/json;charset=utf-8 (791a596a)
2020-05-30T21:01:23.6414896+07:00 0HM04K7GCEPR9:00000004 [INF] Request starting HTTP/1.1 POST http://localhost:44318/api/vi-VN/account/login application/json-patch+json 48 (ca22a1cb)
2020-05-30T21:01:23.7134487+07:00 0HM04K7GCEPR9:00000004 [INF] Route matched with "{action = \"Login\", controller = \"Account\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Login(NiTiAPI.Dapper.ViewModels.LoginViewModel)" on controller "NiTiAPI.Web.Controllers.AccountController" ("NiTiAPI.Web"). (122b2fdf)
2020-05-30T21:01:23.7356966+07:00 0HM04K7GCEPR9:00000004 [INF] Executed action "NiTiAPI.Web.Controllers.AccountController.Login (NiTiAPI.Web)" in 15.7208ms (afa2e885)
2020-05-30T21:01:23.7953808+07:00 0HM04K7GCEPR9:00000004 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[NiTiAPI.Dapper.Models.AppUser]' while attempting to activate 'NiTiAPI.Web.Controllers.AccountController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder.<>c.<<BuildPipeline>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
2020-05-30T21:01:23.8101575+07:00 0HM04K7GCEPR9:00000004 [INF] Request finished in 165.4865ms 500 application/json (791a596a)
2020-05-30T21:01:23.8284376+07:00  [INF] Connection id ""0HM04K7GCEPR9"", Request id ""0HM04K7GCEPR9:00000004"": the application completed without reading the entire request body. (54ac9468)
2020-05-30T21:01:48.6760650+07:00 0HM04K7GCEPRA:00000003 [INF] Request starting HTTP/1.1 POST http://localhost:44318/api/vi-VN/account/login application/json-patch+json 59 (ca22a1cb)
2020-05-30T21:01:48.6789219+07:00 0HM04K7GCEPRA:00000003 [INF] Route matched with "{action = \"Login\", controller = \"Account\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Login(NiTiAPI.Dapper.ViewModels.LoginViewModel)" on controller "NiTiAPI.Web.Controllers.AccountController" ("NiTiAPI.Web"). (122b2fdf)
2020-05-30T21:01:48.6863832+07:00 0HM04K7GCEPRA:00000003 [INF] Executed action "NiTiAPI.Web.Controllers.AccountController.Login (NiTiAPI.Web)" in 4.9426ms (afa2e885)
2020-05-30T21:01:48.6935831+07:00 0HM04K7GCEPRA:00000003 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[NiTiAPI.Dapper.Models.AppUser]' while attempting to activate 'NiTiAPI.Web.Controllers.AccountController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder.<>c.<<BuildPipeline>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
2020-05-30T21:01:48.6981625+07:00 0HM04K7GCEPRA:00000003 [INF] Request finished in 19.7575ms 500 application/json (791a596a)
2020-05-30T21:01:48.7057181+07:00  [INF] Connection id ""0HM04K7GCEPRA"", Request id ""0HM04K7GCEPRA:00000003"": the application completed without reading the entire request body. (54ac9468)
2020-05-30T21:02:07.7900468+07:00 0HM04K7GCEPR8:00000005 [INF] Request starting HTTP/1.1 POST http://localhost:44318/api/vi-VN/account/login application/json-patch+json 59 (ca22a1cb)
2020-05-30T21:02:07.7959006+07:00 0HM04K7GCEPR8:00000005 [INF] Route matched with "{action = \"Login\", controller = \"Account\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Login(NiTiAPI.Dapper.ViewModels.LoginViewModel)" on controller "NiTiAPI.Web.Controllers.AccountController" ("NiTiAPI.Web"). (122b2fdf)
2020-05-30T21:02:07.8006931+07:00 0HM04K7GCEPR8:00000005 [INF] Executed action "NiTiAPI.Web.Controllers.AccountController.Login (NiTiAPI.Web)" in 1.5602ms (afa2e885)
2020-05-30T21:02:07.8086921+07:00 0HM04K7GCEPR8:00000005 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[NiTiAPI.Dapper.Models.AppUser]' while attempting to activate 'NiTiAPI.Web.Controllers.AccountController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder.<>c.<<BuildPipeline>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
2020-05-30T21:02:07.8183415+07:00 0HM04K7GCEPR8:00000005 [INF] Request finished in 21.8681ms 500 application/json (791a596a)
2020-05-30T21:02:07.8289967+07:00  [INF] Connection id ""0HM04K7GCEPR8"", Request id ""0HM04K7GCEPR8:00000005"": the application completed without reading the entire request body. (54ac9468)
2020-05-30T21:02:14.5666102+07:00 0HM04K7GCEPR9:00000005 [INF] Request starting HTTP/1.1 POST http://localhost:44318/api/vi-VN/account/login application/json-patch+json 59 (ca22a1cb)
2020-05-30T21:02:14.5695202+07:00 0HM04K7GCEPR9:00000005 [INF] Route matched with "{action = \"Login\", controller = \"Account\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Login(NiTiAPI.Dapper.ViewModels.LoginViewModel)" on controller "NiTiAPI.Web.Controllers.AccountController" ("NiTiAPI.Web"). (122b2fdf)
2020-05-30T21:02:14.5732727+07:00 0HM04K7GCEPR9:00000005 [INF] Executed action "NiTiAPI.Web.Controllers.AccountController.Login (NiTiAPI.Web)" in 1.9339ms (afa2e885)
2020-05-30T21:02:14.5790489+07:00 0HM04K7GCEPR9:00000005 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[NiTiAPI.Dapper.Models.AppUser]' while attempting to activate 'NiTiAPI.Web.Controllers.AccountController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder.<>c.<<BuildPipeline>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
2020-05-30T21:02:14.5854795+07:00 0HM04K7GCEPR9:00000005 [INF] Request finished in 14.3165ms 500 application/json (791a596a)
2020-05-30T21:02:14.5908477+07:00  [INF] Connection id ""0HM04K7GCEPR9"", Request id ""0HM04K7GCEPR9:00000005"": the application completed without reading the entire request body. (54ac9468)
2020-05-30T21:02:46.4307972+07:00 0HM04K7GCEPRA:00000004 [INF] Request starting HTTP/1.1 POST http://localhost:44318/api/vi-VN/account/login application/json-patch+json 59 (ca22a1cb)
2020-05-30T21:02:46.4342936+07:00 0HM04K7GCEPRA:00000004 [INF] Route matched with "{action = \"Login\", controller = \"Account\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Login(NiTiAPI.Dapper.ViewModels.LoginViewModel)" on controller "NiTiAPI.Web.Controllers.AccountController" ("NiTiAPI.Web"). (122b2fdf)
2020-05-30T21:02:46.4385534+07:00 0HM04K7GCEPRA:00000004 [INF] Executed action "NiTiAPI.Web.Controllers.AccountController.Login (NiTiAPI.Web)" in 1.463ms (afa2e885)
2020-05-30T21:02:46.4441973+07:00 0HM04K7GCEPRA:00000004 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[NiTiAPI.Dapper.Models.AppUser]' while attempting to activate 'NiTiAPI.Web.Controllers.AccountController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder.<>c.<<BuildPipeline>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
2020-05-30T21:02:46.4485081+07:00 0HM04K7GCEPRA:00000004 [INF] Request finished in 16.9078ms 500 application/json (791a596a)
2020-05-30T21:02:46.4574093+07:00  [INF] Connection id ""0HM04K7GCEPRA"", Request id ""0HM04K7GCEPRA:00000004"": the application completed without reading the entire request body. (54ac9468)
2020-05-30T21:02:50.5816518+07:00 0HM04K7GCEPR8:00000006 [INF] Request starting HTTP/1.1 POST http://localhost:44318/api/vi-VN/account/login application/json-patch+json 59 (ca22a1cb)
2020-05-30T21:02:50.5839272+07:00 0HM04K7GCEPR8:00000006 [INF] Route matched with "{action = \"Login\", controller = \"Account\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Login(NiTiAPI.Dapper.ViewModels.LoginViewModel)" on controller "NiTiAPI.Web.Controllers.AccountController" ("NiTiAPI.Web"). (122b2fdf)
2020-05-30T21:02:50.5875997+07:00 0HM04K7GCEPR8:00000006 [INF] Executed action "NiTiAPI.Web.Controllers.AccountController.Login (NiTiAPI.Web)" in 1.4263ms (afa2e885)
2020-05-30T21:02:50.5940047+07:00 0HM04K7GCEPR8:00000006 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[NiTiAPI.Dapper.Models.AppUser]' while attempting to activate 'NiTiAPI.Web.Controllers.AccountController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder.<>c.<<BuildPipeline>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
2020-05-30T21:02:50.6023098+07:00 0HM04K7GCEPR8:00000006 [INF] Request finished in 14.4405ms 500 application/json (791a596a)
2020-05-30T21:02:50.6097262+07:00  [INF] Connection id ""0HM04K7GCEPR8"", Request id ""0HM04K7GCEPR8:00000006"": the application completed without reading the entire request body. (54ac9468)
2020-05-30T21:03:34.3515728+07:00 0HM04K7GCEPRA:00000005 [INF] Request starting HTTP/1.1 POST http://localhost:44318/api/vi-VN/account/login application/json-patch+json 59 (ca22a1cb)
2020-05-30T21:03:34.3572848+07:00 0HM04K7GCEPRA:00000005 [INF] Route matched with "{action = \"Login\", controller = \"Account\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Login(NiTiAPI.Dapper.ViewModels.LoginViewModel)" on controller "NiTiAPI.Web.Controllers.AccountController" ("NiTiAPI.Web"). (122b2fdf)
2020-05-30T21:03:34.3615949+07:00 0HM04K7GCEPRA:00000005 [INF] Executed action "NiTiAPI.Web.Controllers.AccountController.Login (NiTiAPI.Web)" in 1.9894ms (afa2e885)
2020-05-30T21:03:34.3677352+07:00 0HM04K7GCEPRA:00000005 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[NiTiAPI.Dapper.Models.AppUser]' while attempting to activate 'NiTiAPI.Web.Controllers.AccountController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder.<>c.<<BuildPipeline>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
2020-05-30T21:03:34.3755808+07:00 0HM04K7GCEPRA:00000005 [INF] Request finished in 43.7206ms 500 application/json (791a596a)
2020-05-30T21:03:34.3807696+07:00  [INF] Connection id ""0HM04K7GCEPRA"", Request id ""0HM04K7GCEPRA:00000005"": the application completed without reading the entire request body. (54ac9468)
2020-05-30T21:03:34.9205972+07:00 0HM04K7GCEPR8:00000007 [INF] Request starting HTTP/1.1 POST http://localhost:44318/api/vi-VN/account/login application/json-patch+json 59 (ca22a1cb)
2020-05-30T21:03:34.9229168+07:00 0HM04K7GCEPR8:00000007 [INF] Route matched with "{action = \"Login\", controller = \"Account\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Login(NiTiAPI.Dapper.ViewModels.LoginViewModel)" on controller "NiTiAPI.Web.Controllers.AccountController" ("NiTiAPI.Web"). (122b2fdf)
2020-05-30T21:03:34.9261514+07:00 0HM04K7GCEPR8:00000007 [INF] Executed action "NiTiAPI.Web.Controllers.AccountController.Login (NiTiAPI.Web)" in 1.4786ms (afa2e885)
2020-05-30T21:03:34.9325093+07:00 0HM04K7GCEPR8:00000007 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[NiTiAPI.Dapper.Models.AppUser]' while attempting to activate 'NiTiAPI.Web.Controllers.AccountController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder.<>c.<<BuildPipeline>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
2020-05-30T21:03:34.9382923+07:00 0HM04K7GCEPR8:00000007 [INF] Request finished in 14.1033ms 500 application/json (791a596a)
2020-05-30T21:03:34.9438259+07:00  [INF] Connection id ""0HM04K7GCEPR8"", Request id ""0HM04K7GCEPR8:00000007"": the application completed without reading the entire request body. (54ac9468)
2020-05-30T21:03:35.6928417+07:00 0HM04K7GCEPRA:00000006 [INF] Request starting HTTP/1.1 POST http://localhost:44318/api/vi-VN/account/login application/json-patch+json 59 (ca22a1cb)
2020-05-30T21:03:35.6950027+07:00 0HM04K7GCEPRA:00000006 [INF] Route matched with "{action = \"Login\", controller = \"Account\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Login(NiTiAPI.Dapper.ViewModels.LoginViewModel)" on controller "NiTiAPI.Web.Controllers.AccountController" ("NiTiAPI.Web"). (122b2fdf)
2020-05-30T21:03:35.6979958+07:00 0HM04K7GCEPRA:00000006 [INF] Executed action "NiTiAPI.Web.Controllers.AccountController.Login (NiTiAPI.Web)" in 1.3686ms (afa2e885)
2020-05-30T21:03:35.7037584+07:00 0HM04K7GCEPRA:00000006 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[NiTiAPI.Dapper.Models.AppUser]' while attempting to activate 'NiTiAPI.Web.Controllers.AccountController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder.<>c.<<BuildPipeline>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
2020-05-30T21:03:35.7073748+07:00 0HM04K7GCEPRA:00000006 [INF] Request finished in 13.2782ms 500 application/json (791a596a)
2020-05-30T21:03:35.7208245+07:00  [INF] Connection id ""0HM04K7GCEPRA"", Request id ""0HM04K7GCEPRA:00000006"": the application completed without reading the entire request body. (54ac9468)
2020-05-30T21:03:36.8213141+07:00 0HM04K7GCEPR8:00000008 [INF] Request starting HTTP/1.1 POST http://localhost:44318/api/vi-VN/account/login application/json-patch+json 59 (ca22a1cb)
2020-05-30T21:03:36.8237230+07:00 0HM04K7GCEPR8:00000008 [INF] Route matched with "{action = \"Login\", controller = \"Account\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Login(NiTiAPI.Dapper.ViewModels.LoginViewModel)" on controller "NiTiAPI.Web.Controllers.AccountController" ("NiTiAPI.Web"). (122b2fdf)
2020-05-30T21:03:36.8271745+07:00 0HM04K7GCEPR8:00000008 [INF] Executed action "NiTiAPI.Web.Controllers.AccountController.Login (NiTiAPI.Web)" in 1.2266ms (afa2e885)
2020-05-30T21:03:36.8332007+07:00 0HM04K7GCEPR8:00000008 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[NiTiAPI.Dapper.Models.AppUser]' while attempting to activate 'NiTiAPI.Web.Controllers.AccountController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder.<>c.<<BuildPipeline>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
2020-05-30T21:03:36.8375045+07:00 0HM04K7GCEPR8:00000008 [INF] Request finished in 14.2168ms 500 application/json (791a596a)
2020-05-30T21:03:36.8454347+07:00  [INF] Connection id ""0HM04K7GCEPR8"", Request id ""0HM04K7GCEPR8:00000008"": the application completed without reading the entire request body. (54ac9468)
2020-05-30T21:03:59.6487408+07:00 0HM04K7GCEPRA:00000007 [INF] Request starting HTTP/1.1 POST http://localhost:44318/api/vi-VN/account/login application/json-patch+json 59 (ca22a1cb)
2020-05-30T21:03:59.6522767+07:00 0HM04K7GCEPRA:00000007 [INF] Route matched with "{action = \"Login\", controller = \"Account\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Login(NiTiAPI.Dapper.ViewModels.LoginViewModel)" on controller "NiTiAPI.Web.Controllers.AccountController" ("NiTiAPI.Web"). (122b2fdf)
2020-05-30T21:03:59.6558360+07:00 0HM04K7GCEPRA:00000007 [INF] Executed action "NiTiAPI.Web.Controllers.AccountController.Login (NiTiAPI.Web)" in 1.307ms (afa2e885)
2020-05-30T21:03:59.6634957+07:00 0HM04K7GCEPRA:00000007 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[NiTiAPI.Dapper.Models.AppUser]' while attempting to activate 'NiTiAPI.Web.Controllers.AccountController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder.<>c.<<BuildPipeline>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
2020-05-30T21:03:59.6673957+07:00 0HM04K7GCEPRA:00000007 [INF] Request finished in 17.4652ms 500 application/json (791a596a)
2020-05-30T21:03:59.6766469+07:00  [INF] Connection id ""0HM04K7GCEPRA"", Request id ""0HM04K7GCEPRA:00000007"": the application completed without reading the entire request body. (54ac9468)
2020-05-30T21:04:32.0354605+07:00 0HM04K7GCEPR8:00000009 [INF] Request starting HTTP/1.1 GET http://localhost:44318/swagger/index.html   (ca22a1cb)
2020-05-30T21:04:32.0411315+07:00 0HM04K7GCEPR8:00000009 [INF] Request finished in 3.7884ms 200 text/html (791a596a)
2020-05-30T21:04:32.3478866+07:00 0HM04K7GCEPRA:00000008 [INF] Request starting HTTP/1.1 GET http://localhost:44318/swagger/v1/swagger.json   (ca22a1cb)
2020-05-30T21:04:32.3603120+07:00 0HM04K7GCEPRA:00000008 [INF] Request finished in 17.2ms 200 application/json;charset=utf-8 (791a596a)
2020-05-30T21:04:46.6953919+07:00 0HM04K7GCEPR8:0000000A [INF] Request starting HTTP/1.1 POST http://localhost:44318/api/vi-VN/account/login application/json-patch+json 59 (ca22a1cb)
2020-05-30T21:04:46.6983369+07:00 0HM04K7GCEPR8:0000000A [INF] Route matched with "{action = \"Login\", controller = \"Account\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Login(NiTiAPI.Dapper.ViewModels.LoginViewModel)" on controller "NiTiAPI.Web.Controllers.AccountController" ("NiTiAPI.Web"). (122b2fdf)
2020-05-30T21:04:46.7035458+07:00 0HM04K7GCEPR8:0000000A [INF] Executed action "NiTiAPI.Web.Controllers.AccountController.Login (NiTiAPI.Web)" in 2.1731ms (afa2e885)
2020-05-30T21:04:46.7173172+07:00 0HM04K7GCEPR8:0000000A [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[NiTiAPI.Dapper.Models.AppUser]' while attempting to activate 'NiTiAPI.Web.Controllers.AccountController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder.<>c.<<BuildPipeline>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
2020-05-30T21:04:46.7218997+07:00 0HM04K7GCEPR8:0000000A [INF] Request finished in 25.0329ms 500 application/json (791a596a)
2020-05-30T21:04:46.7292528+07:00  [INF] Connection id ""0HM04K7GCEPR8"", Request id ""0HM04K7GCEPR8:0000000A"": the application completed without reading the entire request body. (54ac9468)
2020-05-30T21:06:29.4013861+07:00 0HM04K7GCEPRB:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:44318/api/vi-VN/account/login application/json-patch+json 59 (ca22a1cb)
2020-05-30T21:06:29.4034228+07:00 0HM04K7GCEPRB:00000001 [INF] Route matched with "{action = \"Login\", controller = \"Account\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Login(NiTiAPI.Dapper.ViewModels.LoginViewModel)" on controller "NiTiAPI.Web.Controllers.AccountController" ("NiTiAPI.Web"). (122b2fdf)
2020-05-30T21:06:29.4068060+07:00 0HM04K7GCEPRB:00000001 [INF] Executed action "NiTiAPI.Web.Controllers.AccountController.Login (NiTiAPI.Web)" in 1.4559ms (afa2e885)
2020-05-30T21:06:29.4329197+07:00 0HM04K7GCEPRB:00000001 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[NiTiAPI.Dapper.Models.AppUser]' while attempting to activate 'NiTiAPI.Web.Controllers.AccountController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder.<>c.<<BuildPipeline>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
2020-05-30T21:06:29.4356126+07:00 0HM04K7GCEPRB:00000001 [INF] Request finished in 36.5021ms 500 application/json (791a596a)
2020-05-30T21:06:29.4426441+07:00  [INF] Connection id ""0HM04K7GCEPRB"", Request id ""0HM04K7GCEPRB:00000001"": the application completed without reading the entire request body. (54ac9468)
2020-05-30T21:10:22.0990485+07:00 0HM04KCOEKF2F:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44318/   (ca22a1cb)
2020-05-30T21:10:22.0991829+07:00 0HM04KCOEKF2G:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:58335/  0 (ca22a1cb)
2020-05-30T21:10:22.1659127+07:00 0HM04KCOEKF2G:00000001 [INF] Request finished in 64.1675ms 200  (791a596a)
2020-05-30T21:10:22.6729148+07:00 0HM04KCOEKF2F:00000001 [INF] Request finished in 567.3462ms 404  (791a596a)
2020-05-30T21:10:35.3778199+07:00 0HM04KCOEKF2G:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44318/swagger/index.html   (ca22a1cb)
2020-05-30T21:10:35.4921508+07:00 0HM04KCOEKF2G:00000002 [INF] Request finished in 115.205ms 200 text/html (791a596a)
2020-05-30T21:10:35.8151919+07:00 0HM04KCOEKF2F:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44318/swagger/v1/swagger.json   (ca22a1cb)
2020-05-30T21:10:36.1678082+07:00 0HM04KCOEKF2F:00000002 [INF] Request finished in 353.0506ms 200 application/json;charset=utf-8 (791a596a)
2020-05-30T21:10:54.5440604+07:00 0HM04KCOEKF2G:00000003 [INF] Request starting HTTP/1.1 POST http://localhost:44318/api/vi-VN/account/login application/json-patch+json 48 (ca22a1cb)
2020-05-30T21:10:54.6143591+07:00 0HM04KCOEKF2G:00000003 [INF] Route matched with "{action = \"Login\", controller = \"Account\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Login(NiTiAPI.Dapper.ViewModels.LoginViewModel)" on controller "NiTiAPI.Web.Controllers.AccountController" ("NiTiAPI.Web"). (122b2fdf)
2020-05-30T21:10:54.6377728+07:00 0HM04KCOEKF2G:00000003 [INF] Executed action "NiTiAPI.Web.Controllers.AccountController.Login (NiTiAPI.Web)" in 15.5199ms (afa2e885)
2020-05-30T21:10:54.6905010+07:00 0HM04KCOEKF2G:00000003 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[NiTiAPI.Dapper.Models.AppUser]' while attempting to activate 'NiTiAPI.Web.Controllers.AccountController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder.<>c.<<BuildPipeline>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
2020-05-30T21:10:54.7072624+07:00 0HM04KCOEKF2G:00000003 [INF] Request finished in 162.0656ms 500 application/json (791a596a)
2020-05-30T21:10:54.7273624+07:00  [INF] Connection id ""0HM04KCOEKF2G"", Request id ""0HM04KCOEKF2G:00000003"": the application completed without reading the entire request body. (54ac9468)
2020-05-30T21:12:44.6533154+07:00 0HM04KCOEKF2H:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:44318/api/vi-VN/account/login application/json-patch+json 48 (ca22a1cb)
2020-05-30T21:12:44.6561176+07:00 0HM04KCOEKF2H:00000001 [INF] Route matched with "{action = \"Login\", controller = \"Account\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Login(NiTiAPI.Dapper.ViewModels.LoginViewModel)" on controller "NiTiAPI.Web.Controllers.AccountController" ("NiTiAPI.Web"). (122b2fdf)
2020-05-30T21:12:44.6654850+07:00 0HM04KCOEKF2H:00000001 [INF] Executed action "NiTiAPI.Web.Controllers.AccountController.Login (NiTiAPI.Web)" in 6.6709ms (afa2e885)
2020-05-30T21:12:44.6758458+07:00 0HM04KCOEKF2H:00000001 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[NiTiAPI.Dapper.Models.AppUser]' while attempting to activate 'NiTiAPI.Web.Controllers.AccountController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder.<>c.<<BuildPipeline>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
2020-05-30T21:12:44.6806243+07:00 0HM04KCOEKF2H:00000001 [INF] Request finished in 25.309ms 500 application/json (791a596a)
2020-05-30T21:12:44.6872471+07:00  [INF] Connection id ""0HM04KCOEKF2H"", Request id ""0HM04KCOEKF2H:00000001"": the application completed without reading the entire request body. (54ac9468)
2020-05-30T21:12:45.8833141+07:00 0HM04KCOEKF2H:00000002 [INF] Request starting HTTP/1.1 POST http://localhost:44318/api/vi-VN/account/login application/json-patch+json 48 (ca22a1cb)
2020-05-30T21:12:45.8872171+07:00 0HM04KCOEKF2H:00000002 [INF] Route matched with "{action = \"Login\", controller = \"Account\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Login(NiTiAPI.Dapper.ViewModels.LoginViewModel)" on controller "NiTiAPI.Web.Controllers.AccountController" ("NiTiAPI.Web"). (122b2fdf)
2020-05-30T21:12:45.8990422+07:00 0HM04KCOEKF2H:00000002 [INF] Executed action "NiTiAPI.Web.Controllers.AccountController.Login (NiTiAPI.Web)" in 2.6939ms (afa2e885)
2020-05-30T21:12:45.9167356+07:00 0HM04KCOEKF2H:00000002 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[NiTiAPI.Dapper.Models.AppUser]' while attempting to activate 'NiTiAPI.Web.Controllers.AccountController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder.<>c.<<BuildPipeline>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
2020-05-30T21:12:45.9227758+07:00 0HM04KCOEKF2H:00000002 [INF] Request finished in 39.5667ms 500 application/json (791a596a)
2020-05-30T21:12:45.9317146+07:00  [INF] Connection id ""0HM04KCOEKF2H"", Request id ""0HM04KCOEKF2H:00000002"": the application completed without reading the entire request body. (54ac9468)
2020-05-30T21:12:46.3596885+07:00 0HM04KCOEKF2H:00000003 [INF] Request starting HTTP/1.1 POST http://localhost:44318/api/vi-VN/account/login application/json-patch+json 48 (ca22a1cb)
2020-05-30T21:12:46.3639838+07:00 0HM04KCOEKF2H:00000003 [INF] Route matched with "{action = \"Login\", controller = \"Account\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Login(NiTiAPI.Dapper.ViewModels.LoginViewModel)" on controller "NiTiAPI.Web.Controllers.AccountController" ("NiTiAPI.Web"). (122b2fdf)
2020-05-30T21:12:46.3671489+07:00 0HM04KCOEKF2H:00000003 [INF] Executed action "NiTiAPI.Web.Controllers.AccountController.Login (NiTiAPI.Web)" in 1.3835ms (afa2e885)
2020-05-30T21:12:46.3735556+07:00 0HM04KCOEKF2H:00000003 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[NiTiAPI.Dapper.Models.AppUser]' while attempting to activate 'NiTiAPI.Web.Controllers.AccountController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder.<>c.<<BuildPipeline>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
2020-05-30T21:12:46.3766921+07:00 0HM04KCOEKF2H:00000003 [INF] Request finished in 16.0668ms 500 application/json (791a596a)
2020-05-30T21:12:46.3911798+07:00  [INF] Connection id ""0HM04KCOEKF2H"", Request id ""0HM04KCOEKF2H:00000003"": the application completed without reading the entire request body. (54ac9468)
2020-05-30T21:12:46.9204533+07:00 0HM04KCOEKF2H:00000004 [INF] Request starting HTTP/1.1 POST http://localhost:44318/api/vi-VN/account/login application/json-patch+json 48 (ca22a1cb)
2020-05-30T21:12:46.9227236+07:00 0HM04KCOEKF2H:00000004 [INF] Route matched with "{action = \"Login\", controller = \"Account\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Login(NiTiAPI.Dapper.ViewModels.LoginViewModel)" on controller "NiTiAPI.Web.Controllers.AccountController" ("NiTiAPI.Web"). (122b2fdf)
2020-05-30T21:12:46.9260794+07:00 0HM04KCOEKF2H:00000004 [INF] Executed action "NiTiAPI.Web.Controllers.AccountController.Login (NiTiAPI.Web)" in 1.3305ms (afa2e885)
2020-05-30T21:12:46.9361483+07:00 0HM04KCOEKF2H:00000004 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[NiTiAPI.Dapper.Models.AppUser]' while attempting to activate 'NiTiAPI.Web.Controllers.AccountController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder.<>c.<<BuildPipeline>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
2020-05-30T21:12:46.9459874+07:00 0HM04KCOEKF2H:00000004 [INF] Request finished in 18.0136ms 500 application/json (791a596a)
2020-05-30T21:12:46.9537928+07:00  [INF] Connection id ""0HM04KCOEKF2H"", Request id ""0HM04KCOEKF2H:00000004"": the application completed without reading the entire request body. (54ac9468)
2020-05-30T21:12:47.3531727+07:00 0HM04KCOEKF2H:00000005 [INF] Request starting HTTP/1.1 POST http://localhost:44318/api/vi-VN/account/login application/json-patch+json 48 (ca22a1cb)
2020-05-30T21:12:47.3552617+07:00 0HM04KCOEKF2H:00000005 [INF] Route matched with "{action = \"Login\", controller = \"Account\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Login(NiTiAPI.Dapper.ViewModels.LoginViewModel)" on controller "NiTiAPI.Web.Controllers.AccountController" ("NiTiAPI.Web"). (122b2fdf)
2020-05-30T21:12:47.3594034+07:00 0HM04KCOEKF2H:00000005 [INF] Executed action "NiTiAPI.Web.Controllers.AccountController.Login (NiTiAPI.Web)" in 1.4266ms (afa2e885)
2020-05-30T21:12:47.3669700+07:00 0HM04KCOEKF2H:00000005 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[NiTiAPI.Dapper.Models.AppUser]' while attempting to activate 'NiTiAPI.Web.Controllers.AccountController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder.<>c.<<BuildPipeline>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
2020-05-30T21:12:47.3942704+07:00 0HM04KCOEKF2H:00000005 [INF] Request finished in 16.4815ms 500 application/json (791a596a)
2020-05-30T21:12:47.3994653+07:00  [INF] Connection id ""0HM04KCOEKF2H"", Request id ""0HM04KCOEKF2H:00000005"": the application completed without reading the entire request body. (54ac9468)
2020-05-30T21:12:47.7684299+07:00 0HM04KCOEKF2H:00000006 [INF] Request starting HTTP/1.1 POST http://localhost:44318/api/vi-VN/account/login application/json-patch+json 48 (ca22a1cb)
2020-05-30T21:12:47.7743395+07:00 0HM04KCOEKF2H:00000006 [INF] Route matched with "{action = \"Login\", controller = \"Account\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Login(NiTiAPI.Dapper.ViewModels.LoginViewModel)" on controller "NiTiAPI.Web.Controllers.AccountController" ("NiTiAPI.Web"). (122b2fdf)
2020-05-30T21:12:47.7839406+07:00 0HM04KCOEKF2H:00000006 [INF] Executed action "NiTiAPI.Web.Controllers.AccountController.Login (NiTiAPI.Web)" in 6.5698ms (afa2e885)
2020-05-30T21:12:47.7967801+07:00 0HM04KCOEKF2H:00000006 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[NiTiAPI.Dapper.Models.AppUser]' while attempting to activate 'NiTiAPI.Web.Controllers.AccountController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder.<>c.<<BuildPipeline>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
2020-05-30T21:12:47.8132204+07:00 0HM04KCOEKF2H:00000006 [INF] Request finished in 137.414ms 500 application/json (791a596a)
2020-05-30T21:12:47.8333105+07:00  [INF] Connection id ""0HM04KCOEKF2H"", Request id ""0HM04KCOEKF2H:00000006"": the application completed without reading the entire request body. (54ac9468)
2020-05-30T21:12:47.9405672+07:00 0HM04KCOEKF2H:00000007 [INF] Request starting HTTP/1.1 POST http://localhost:44318/api/vi-VN/account/login application/json-patch+json 48 (ca22a1cb)
2020-05-30T21:12:47.9446389+07:00 0HM04KCOEKF2H:00000007 [INF] Route matched with "{action = \"Login\", controller = \"Account\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Login(NiTiAPI.Dapper.ViewModels.LoginViewModel)" on controller "NiTiAPI.Web.Controllers.AccountController" ("NiTiAPI.Web"). (122b2fdf)
2020-05-30T21:12:47.9483702+07:00 0HM04KCOEKF2H:00000007 [INF] Executed action "NiTiAPI.Web.Controllers.AccountController.Login (NiTiAPI.Web)" in 1.5397ms (afa2e885)
2020-05-30T21:12:47.9562712+07:00 0HM04KCOEKF2H:00000007 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[NiTiAPI.Dapper.Models.AppUser]' while attempting to activate 'NiTiAPI.Web.Controllers.AccountController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder.<>c.<<BuildPipeline>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
2020-05-30T21:12:47.9634341+07:00 0HM04KCOEKF2H:00000007 [INF] Request finished in 18.4207ms 500 application/json (791a596a)
2020-05-30T21:12:47.9715807+07:00  [INF] Connection id ""0HM04KCOEKF2H"", Request id ""0HM04KCOEKF2H:00000007"": the application completed without reading the entire request body. (54ac9468)
2020-05-30T21:12:49.7892732+07:00 0HM04KCOEKF2H:00000008 [INF] Request starting HTTP/1.1 POST http://localhost:44318/api/vi-VN/account/login application/json-patch+json 48 (ca22a1cb)
2020-05-30T21:12:49.7937441+07:00 0HM04KCOEKF2H:00000008 [INF] Route matched with "{action = \"Login\", controller = \"Account\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Login(NiTiAPI.Dapper.ViewModels.LoginViewModel)" on controller "NiTiAPI.Web.Controllers.AccountController" ("NiTiAPI.Web"). (122b2fdf)
2020-05-30T21:12:49.7990072+07:00 0HM04KCOEKF2H:00000008 [INF] Executed action "NiTiAPI.Web.Controllers.AccountController.Login (NiTiAPI.Web)" in 1.7355ms (afa2e885)
2020-05-30T21:12:49.8095945+07:00 0HM04KCOEKF2H:00000008 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[NiTiAPI.Dapper.Models.AppUser]' while attempting to activate 'NiTiAPI.Web.Controllers.AccountController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder.<>c.<<BuildPipeline>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
2020-05-30T21:12:49.8173076+07:00 0HM04KCOEKF2H:00000008 [INF] Request finished in 25.0593ms 500 application/json (791a596a)
2020-05-30T21:12:49.8297772+07:00  [INF] Connection id ""0HM04KCOEKF2H"", Request id ""0HM04KCOEKF2H:00000008"": the application completed without reading the entire request body. (54ac9468)
2020-05-30T21:14:42.7442444+07:00 0HM04KF63T2UN:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:58335/  0 (ca22a1cb)
2020-05-30T21:14:42.7442444+07:00 0HM04KF63T2UM:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44318/   (ca22a1cb)
2020-05-30T21:14:42.8033618+07:00 0HM04KF63T2UN:00000001 [INF] Request finished in 66.8503ms 200  (791a596a)
2020-05-30T21:14:43.1672692+07:00 0HM04KF63T2UM:00000001 [INF] Request finished in 418.9191ms 404  (791a596a)
2020-05-30T21:14:43.8602593+07:00 0HM04KF63T2UN:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44318/swagger/index.html   (ca22a1cb)
2020-05-30T21:14:44.0826652+07:00 0HM04KF63T2UN:00000002 [INF] Request finished in 227.7104ms 200 text/html (791a596a)
2020-05-30T21:14:44.4848129+07:00 0HM04KF63T2UM:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44318/swagger/v1/swagger.json   (ca22a1cb)
2020-05-30T21:14:44.8271107+07:00 0HM04KF63T2UM:00000002 [INF] Request finished in 344.3523ms 200 application/json;charset=utf-8 (791a596a)
2020-05-30T21:15:30.6814020+07:00 0HM04KF63T2UN:00000003 [INF] Request starting HTTP/1.1 POST http://localhost:44318/api/vi-VN/account/register application/json-patch+json 108 (ca22a1cb)
2020-05-30T21:15:30.7632807+07:00 0HM04KF63T2UN:00000003 [INF] Route matched with "{action = \"Register\", controller = \"Account\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Register(NiTiAPI.Dapper.ViewModels.RegisterViewModel)" on controller "NiTiAPI.Web.Controllers.AccountController" ("NiTiAPI.Web"). (122b2fdf)
2020-05-30T21:15:30.7981836+07:00 0HM04KF63T2UN:00000003 [INF] Executed action "NiTiAPI.Web.Controllers.AccountController.Register (NiTiAPI.Web)" in 21.9394ms (afa2e885)
2020-05-30T21:15:30.8538460+07:00 0HM04KF63T2UN:00000003 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[NiTiAPI.Dapper.Models.AppUser]' while attempting to activate 'NiTiAPI.Web.Controllers.AccountController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder.<>c.<<BuildPipeline>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
2020-05-30T21:15:30.8787776+07:00 0HM04KF63T2UN:00000003 [INF] Request finished in 188.282ms 500 application/json (791a596a)
2020-05-30T21:15:30.9039301+07:00  [INF] Connection id ""0HM04KF63T2UN"", Request id ""0HM04KF63T2UN:00000003"": the application completed without reading the entire request body. (54ac9468)
2020-05-30T21:18:25.3190072+07:00 0HM04KH8ESSB3:00000001 [INF] Request starting HTTP/1.1 DEBUG http://localhost:58335/  0 (ca22a1cb)
2020-05-30T21:18:25.3190529+07:00 0HM04KH8ESSB2:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44318/   (ca22a1cb)
2020-05-30T21:18:25.4228156+07:00 0HM04KH8ESSB3:00000001 [INF] Request finished in 84.1223ms 200  (791a596a)
2020-05-30T21:18:25.7901558+07:00 0HM04KH8ESSB2:00000001 [INF] Request finished in 442.1341ms 404  (791a596a)
2020-05-30T21:18:26.8189003+07:00 0HM04KH8ESSB3:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44318/swagger/index.html   (ca22a1cb)
2020-05-30T21:18:26.9460930+07:00 0HM04KH8ESSB3:00000002 [INF] Request finished in 127.529ms 200 text/html (791a596a)
2020-05-30T21:18:27.1558605+07:00 0HM04KH8ESSB2:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:44318/swagger/v1/swagger.json   (ca22a1cb)
2020-05-30T21:18:27.4402221+07:00 0HM04KH8ESSB2:00000002 [INF] Request finished in 283.818ms 200 application/json;charset=utf-8 (791a596a)
2020-05-30T21:18:40.6574718+07:00 0HM04KH8ESSB3:00000003 [INF] Request starting HTTP/1.1 POST http://localhost:44318/api/vi-VN/account/login application/json-patch+json 48 (ca22a1cb)
2020-05-30T21:18:40.7442786+07:00 0HM04KH8ESSB3:00000003 [INF] Route matched with "{action = \"Login\", controller = \"Account\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Login(NiTiAPI.Dapper.ViewModels.LoginViewModel)" on controller "NiTiAPI.Web.Controllers.AccountController" ("NiTiAPI.Web"). (122b2fdf)
2020-05-30T21:18:40.7679472+07:00 0HM04KH8ESSB3:00000003 [INF] Executed action "NiTiAPI.Web.Controllers.AccountController.Login (NiTiAPI.Web)" in 17.1548ms (afa2e885)
2020-05-30T21:18:40.8208689+07:00 0HM04KH8ESSB3:00000003 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[NiTiAPI.Dapper.Models.AppUser]' while attempting to activate 'NiTiAPI.Web.Controllers.AccountController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder.<>c.<<BuildPipeline>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
2020-05-30T21:18:40.8339077+07:00 0HM04KH8ESSB3:00000003 [INF] Request finished in 175.642ms 500 application/json (791a596a)
2020-05-30T21:18:40.8546093+07:00  [INF] Connection id ""0HM04KH8ESSB3"", Request id ""0HM04KH8ESSB3:00000003"": the application completed without reading the entire request body. (54ac9468)
2020-05-30T21:19:45.5512298+07:00 0HM04KH8ESSB4:00000001 [INF] Request starting HTTP/1.1 POST http://localhost:44318/api/vi-VN/account/register application/json-patch+json 108 (ca22a1cb)
2020-05-30T21:19:45.5648227+07:00 0HM04KH8ESSB4:00000001 [INF] Route matched with "{action = \"Register\", controller = \"Account\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Register(NiTiAPI.Dapper.ViewModels.RegisterViewModel)" on controller "NiTiAPI.Web.Controllers.AccountController" ("NiTiAPI.Web"). (122b2fdf)
2020-05-30T21:19:45.5779796+07:00 0HM04KH8ESSB4:00000001 [INF] Executed action "NiTiAPI.Web.Controllers.AccountController.Register (NiTiAPI.Web)" in 11.1308ms (afa2e885)
2020-05-30T21:19:45.5854434+07:00 0HM04KH8ESSB4:00000001 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[NiTiAPI.Dapper.Models.AppUser]' while attempting to activate 'NiTiAPI.Web.Controllers.AccountController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder.<>c.<<BuildPipeline>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
2020-05-30T21:19:45.5927240+07:00 0HM04KH8ESSB4:00000001 [INF] Request finished in 38.9001ms 500 application/json (791a596a)
2020-05-30T21:19:45.6059746+07:00  [INF] Connection id ""0HM04KH8ESSB4"", Request id ""0HM04KH8ESSB4:00000001"": the application completed without reading the entire request body. (54ac9468)
2020-05-30T21:20:58.1479257+07:00 0HM04KH8ESSB5:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:44318/api/function   (ca22a1cb)
2020-05-30T21:20:58.1561032+07:00 0HM04KH8ESSB5:00000001 [INF] Route matched with "{action = \"Get\", controller = \"Function\"}". Executing controller action with signature "System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get()" on controller "NiTiAPI.Web.Controllers.FunctionController" ("NiTiAPI.Web"). (122b2fdf)
2020-05-30T21:20:58.1724804+07:00 0HM04KH8ESSB5:00000001 [INF] Executing action method "NiTiAPI.Web.Controllers.FunctionController.Get (NiTiAPI.Web)" - Validation state: Valid (dad538d7)
2020-05-30T21:20:58.9999674+07:00 0HM04KH8ESSB5:00000001 [INF] Executed action method "NiTiAPI.Web.Controllers.FunctionController.Get (NiTiAPI.Web)", returned result "Microsoft.AspNetCore.Mvc.OkObjectResult" in 817.4648ms. (50a9e262)
2020-05-30T21:20:59.0181932+07:00 0HM04KH8ESSB5:00000001 [INF] Executing ObjectResult, writing value of type '"System.Collections.Generic.List`1[[NiTiAPI.Dapper.Models.Function, NiTiAPI.Dapper, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]"'. (8a1b66c8)
2020-05-30T21:20:59.0352676+07:00 0HM04KH8ESSB5:00000001 [INF] Executed action "NiTiAPI.Web.Controllers.FunctionController.Get (NiTiAPI.Web)" in 876.8969ms (afa2e885)
2020-05-30T21:20:59.0499512+07:00 0HM04KH8ESSB5:00000001 [INF] Request finished in 905.7497ms 200 application/json; charset=utf-8 (791a596a)
